# -*- coding: utf-8 -*-
"""Blind_Motion_Deblurring_via_Cepstral_PSF_Estimation_and_Forward_Consistent_Wiener_Regularization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ROyM28tCNiKVJhN0TaMuRwzk3ogl2Kuj
"""

# -*- coding: utf-8 -*-
"""
PSF Estimator Comparison
========================
Estimate (L, θ) from a blurred image using three approaches:
  1. Radon on log-spectrum
  2. Cepstrum
  3. Gradient histogram (θ only) + consistency sweep (L + fine θ)

No deblurring — just measure how well each method recovers the true PSF.
"""

import numpy as np
import scipy.ndimage as ndimage
from scipy.fft import fft2, ifft2, fftshift
from scipy.signal import find_peaks
from skimage import data, color
from skimage.transform import resize, radon
from skimage.metrics import peak_signal_noise_ratio as psnr
from skimage.filters import sobel_h, sobel_v
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import warnings

warnings.filterwarnings('ignore')
np.random.seed(42)
plt.style.use('dark_background')
plt.rcParams.update({'figure.dpi': 130, 'font.size': 11})

# ─────────────────────────────────────────────────────────────────────────────
# Forward model
# ─────────────────────────────────────────────────────────────────────────────

def load_image():
    img = color.rgb2gray(data.astronaut()).astype(np.float64)
    return img / img.max()

def make_motion_psf(length=25, angle=45.0, size=None):
    if size is None:
        size = length + 4 if length % 2 == 0 else length + 3
    psf = np.zeros((size, size))
    cx, cy = size // 2, size // 2
    angle_rad = np.deg2rad(angle)
    for t in np.linspace(-(length-1)/2, (length-1)/2, length*4):
        x = int(round(cx + t * np.cos(angle_rad)))
        y = int(round(cy + t * np.sin(angle_rad)))
        if 0 <= x < size and 0 <= y < size:
            psf[y, x] = 1.0
    return psf / psf.sum()

def degrade(img, psf, sigma=0.01):
    blurred = ndimage.convolve(img, psf, mode='wrap')
    return np.clip(blurred + np.random.normal(0, sigma, img.shape), 0, 1)

def psf_to_otf(psf, shape):
    pad = np.zeros(shape)
    ph, pw = psf.shape
    pad[:ph, :pw] = psf
    pad = np.roll(pad, (-ph//2, -pw//2), axis=(0, 1))
    return fft2(pad)

def wiener(g, psf, K=1e-3):
    G = fft2(g)
    H = psf_to_otf(psf, g.shape)
    return np.clip(np.real(ifft2((np.conj(H) / (np.abs(H)**2 + K)) * G)), 0, 1)

f_true = load_image()

BLUR_CONFIGS = [
    {'length': 25, 'angle':   0, 'label': 'Horizontal  L=25'},
    {'length': 35, 'angle': 135, 'label': 'Anti-diag   L=35'},
]
SIGMA_NOISE = 0.01
PSF_SIZE    = 39   # fixed canvas for all estimated PSFs

cases = []
for cfg in BLUR_CONFIGS:
    psf = make_motion_psf(cfg['length'], cfg['angle'], size=PSF_SIZE)
    g   = degrade(f_true, psf, SIGMA_NOISE)
    cases.append({'psf': psf, 'g': g, **cfg})

print('Forward model ready.')


# ─────────────────────────────────────────────────────────────────────────────
# Shared helper: angular error (handles 180° ambiguity in line orientation)
# ─────────────────────────────────────────────────────────────────────────────

def angle_err(est, true):
    """Smallest angular difference accounting for 180° line symmetry."""
    d = abs(est - true) % 180
    return min(d, 180 - d)

def psf_l2(h_est, h_true):
    """L2 distance between two PSFs normalised to the same canvas."""
    return np.linalg.norm(h_est - h_true)


# ─────────────────────────────────────────────────────────────────────────────
# Method 1 — Radon on log-spectrum
# ─────────────────────────────────────────────────────────────────────────────

def estimate_psf_radon(g, psf_size, sigma_noise=0.01):
    H, W = g.shape
    cy, cx = H // 2, W // 2

    G_mag = np.abs(fftshift(fft2(g)))
    G_log = np.log1p(G_mag)
    mask_r = max(int(0.03 * min(H, W)), 3)
    G_log[cy-mask_r:cy+mask_r, cx-mask_r:cx+mask_r] = 0.0
    G_log = (G_log - G_log.min()) / (G_log.max() - G_log.min() + 1e-8)

    crop_sz = min(H, W, 256)
    r0 = cy - crop_sz // 2; c0 = cx - crop_sz // 2
    G_crop = G_log[r0:r0+crop_sz, c0:c0+crop_sz]

    thetas = np.arange(0, 180, 1, dtype=float)
    sino   = radon(G_crop, theta=thetas, circle=True)

    # Min-variance column = projection along null stripes = blur direction
    col_vars     = sino.var(axis=0)
    best_ang_idx = int(np.argmin(col_vars))
    theta_est    = thetas[best_ang_idx]

    # Estimate L: slice log-spectrum along blur direction, find first null
    half  = crop_sz // 2
    t_vals = np.arange(-half, half)
    ang_r  = np.deg2rad(theta_est)
    xs = (cx - c0) + t_vals * np.cos(ang_r)
    ys = (cy - r0) + t_vals * np.sin(ang_r)
    valid = (xs >= 0) & (xs < crop_sz) & (ys >= 0) & (ys < crop_sz)
    xs, ys, t_vals = xs[valid], ys[valid], t_vals[valid]
    profile = G_crop[np.round(ys).astype(int), np.round(xs).astype(int)]
    freq    = np.abs(t_vals) / crop_sz

    inv_profile = profile.max() - profile
    peaks_idx, _ = find_peaks(inv_profile,
                               height=0.1 * inv_profile.max(), distance=3)
    peaks_idx = peaks_idx[freq[peaks_idx] > 0.02]
    if len(peaks_idx) > 0:
        L_est = int(round(1.0 / (2.0 * freq[peaks_idx[0]] + 1e-8)))
    else:
        cum = np.cumsum(profile[len(profile)//2:])
        cum /= cum[-1] + 1e-8
        idx90 = int(np.searchsorted(cum, 0.90))
        L_est = max(5, int(round(crop_sz / (2 * max(idx90, 1)))))

    L_est = int(np.clip(L_est, 3, psf_size - 2))
    return make_motion_psf(L_est, theta_est, size=psf_size), L_est, theta_est


# ─────────────────────────────────────────────────────────────────────────────
# Method 2 — Cepstrum
# ─────────────────────────────────────────────────────────────────────────────

def estimate_psf_cepstrum(g, psf_size, sigma_noise=0.01):
    H, W = g.shape
    cy, cx = H // 2, W // 2

    # Power cepstrum: IFFT of log(|FFT(g)|^2)
    G_mag2 = np.abs(fft2(g)) ** 2
    log_ps = np.log(G_mag2 + 1e-10)
    cepstrum = np.real(ifft2(log_ps))
    cepstrum = fftshift(cepstrum)

    # Suppress DC and near-DC (centre region)
    mask_r = max(int(0.04 * min(H, W)), 5)
    cep_masked = cepstrum.copy()
    cep_masked[cy-mask_r:cy+mask_r, cx-mask_r:cx+mask_r] = 0.0

    # Suppress edges (wrap-around artifacts)
    edge = max(int(0.1 * min(H, W)), 10)
    cep_masked[:edge, :] = 0; cep_masked[-edge:, :] = 0
    cep_masked[:, :edge] = 0; cep_masked[:, -edge:] = 0

    # Motion blur → two symmetric peaks at (±dy, ±dx) from centre
    # Only search upper half to avoid duplicate
    search = cep_masked.copy()
    search[cy:, :] = 0   # upper half only

    peak_idx = np.unravel_index(np.argmax(np.abs(search)), search.shape)
    dy = cy - peak_idx[0]   # row offset from centre
    dx = peak_idx[1] - cx   # col offset from centre

    L_est     = int(round(np.sqrt(dx**2 + dy**2)))
    theta_raw = np.degrees(np.arctan2(dy, dx)) % 180
    L_est     = int(np.clip(L_est, 3, psf_size - 2))

    # Resolve 180 deg ambiguity: try theta, theta+90, theta-90
    # Score each via forward consistency — correct PSF reconstructs g better
    K = sigma_noise ** 2 * 50
    candidates = [theta_raw, (theta_raw + 90) % 180, (theta_raw - 90) % 180]
    best_psf, best_theta, best_score = None, theta_raw, np.inf
    for th in candidates:
        h_try = make_motion_psf(L_est, th, size=psf_size)
        f_try = wiener(g, h_try, K=K)
        score = np.linalg.norm(ndimage.convolve(f_try, h_try, mode="wrap") - g)
        if score < best_score:
            best_score, best_theta, best_psf = score, th, h_try
    return best_psf, L_est, best_theta


# ─────────────────────────────────────────────────────────────────────────────
# Method 3 — Gradient histogram (θ) + consistency sweep (L + fine θ)
# ─────────────────────────────────────────────────────────────────────────────

def estimate_psf_grad_sweep(g, psf_size, sigma_noise=0.01,
                             L_range=range(5, 40, 2),
                             theta_coarse_step=15):
    # ── Step A: gradient histogram → blur angle ───────────────────────────
    # Motion blur suppresses gradients perpendicular to blur direction.
    # The *depleted* orientation bin in the gradient histogram = blur angle.
    gx = sobel_v(g)   # horizontal gradient (d/dx)
    gy = sobel_h(g)   # vertical gradient   (d/dy)
    mag   = np.sqrt(gx**2 + gy**2)
    # Only use strong gradients (top 30%) — weak ones are noise
    thresh = np.percentile(mag, 70)
    mask   = mag > thresh
    angles = np.degrees(np.arctan2(gy[mask], gx[mask])) % 180

    # Histogram over [0, 180)
    n_bins = 36
    hist, bin_edges = np.histogram(angles, bins=n_bins, range=(0, 180))
    bin_centres = (bin_edges[:-1] + bin_edges[1:]) / 2

    # Smooth histogram to avoid bin-edge sensitivity
    from scipy.ndimage import uniform_filter1d
    hist_smooth = uniform_filter1d(hist.astype(float), size=3, mode='wrap')

    # Blur direction = bin with minimum gradient energy (depleted orientation)
    theta_coarse = float(bin_centres[np.argmin(hist_smooth)])

    # ── Step B: forward-model consistency sweep ───────────────────────────
    # Search L × fine-θ grid around the gradient estimate.
    # Score = ||convolve(wiener(g, h), h) - g||  (blind, no f_true needed)
    theta_fine_range = np.arange(theta_coarse - 20,
                                  theta_coarse + 21,
                                  5)

    best_L, best_theta, best_score = 5, theta_coarse, np.inf
    K = sigma_noise ** 2 * 50   # fixed Wiener K for scoring

    for L_try in L_range:
        for th_try in theta_fine_range:
            h_try  = make_motion_psf(L_try, th_try % 180, size=psf_size)
            f_try  = wiener(g, h_try, K=K)
            score  = np.linalg.norm(
                ndimage.convolve(f_try, h_try, mode='wrap') - g
            )
            if score < best_score:
                best_score = score
                best_L, best_theta = L_try, th_try % 180

    return (make_motion_psf(best_L, best_theta, size=psf_size),
            best_L, best_theta)


# ─────────────────────────────────────────────────────────────────────────────
# Run all methods on all cases
# ─────────────────────────────────────────────────────────────────────────────

METHODS = {
    'Radon':       estimate_psf_radon,
    'Cepstrum':    estimate_psf_cepstrum,
    'Grad+Sweep':  estimate_psf_grad_sweep,
}

print(f"\n{'─'*72}")
print(f"  {'Case':<22}  {'Method':<14}  {'True L':>6}  {'Est L':>6}  "
      f"{'ΔL':>5}  {'True θ':>7}  {'Est θ':>7}  {'Δθ':>6}  {'PSF L2':>8}")
print(f"{'─'*72}")

results = []
for c in cases:
    for mname, mfunc in METHODS.items():
        h_est, L_est, theta_est = mfunc(c['g'], PSF_SIZE, SIGMA_NOISE)
        dL   = abs(L_est - c['length'])
        dth  = angle_err(theta_est, c['angle'])
        l2   = psf_l2(h_est, c['psf'])
        print(f"  {c['label']:<22}  {mname:<14}  {c['length']:>6}  {L_est:>6}  "
              f"{dL:>5}  {c['angle']:>7.1f}  {theta_est:>7.1f}  {dth:>6.1f}  {l2:>8.4f}")
        results.append({
            'case': c['label'], 'method': mname,
            'true_L': c['length'], 'est_L': L_est, 'dL': dL,
            'true_theta': c['angle'], 'est_theta': theta_est,
            'dtheta': dth, 'psf_l2': l2,
            'h_est': h_est, 'h_true': c['psf'],
        })
    print(f"{'─'*72}")


# ─────────────────────────────────────────────────────────────────────────────
# Visualise: true PSF vs each method's estimate
# ─────────────────────────────────────────────────────────────────────────────

n_cases   = len(cases)
n_methods = len(METHODS)
n_cols    = 1 + n_methods   # true + one per method

fig, axes = plt.subplots(n_cases, n_cols,
                          figsize=(3.5 * n_cols, 3.5 * n_cases))
fig.suptitle('PSF Estimation — True vs Estimated', fontsize=13, y=1.01)

col_titles = ['True PSF'] + list(METHODS.keys())

def psf_pad_disp(psf, size=PSF_SIZE):
    d = np.zeros((size, size))
    ph, pw = psf.shape
    r = max(size//2 - ph//2, 0); c = max(size//2 - pw//2, 0)
    d[r:r+ph, c:c+pw] = psf
    return d / (d.max() + 1e-8)

for row, c in enumerate(cases):
    # True PSF
    axes[row, 0].imshow(psf_pad_disp(c['psf']), cmap='hot', vmin=0, vmax=1)
    axes[row, 0].set_ylabel(c['label'], fontsize=9)
    axes[row, 0].set_title('True PSF' if row == 0 else '', fontsize=9)
    axes[row, 0].set_xlabel(f"L={c['length']}  θ={c['angle']}°", fontsize=8)
    axes[row, 0].axis('off')

    # Each method
    case_results = [r for r in results if r['case'] == c['label']]
    for col, res in enumerate(case_results, start=1):
        axes[row, col].imshow(psf_pad_disp(res['h_est']), cmap='hot', vmin=0, vmax=1)
        axes[row, col].set_title(res['method'] if row == 0 else '', fontsize=9)
        axes[row, col].set_xlabel(
            f"L={res['est_L']} (Δ{res['dL']})  "
            f"θ={res['est_theta']:.0f}° (Δ{res['dtheta']:.0f}°)\n"
            f"L2={res['psf_l2']:.3f}",
            fontsize=7.5
        )
        axes[row, col].axis('off')

plt.tight_layout()
plt.savefig('psf_estimation_comparison.png', dpi=130, bbox_inches='tight')
plt.show()


# ─────────────────────────────────────────────────────────────────────────────
# Summary bar chart
# ─────────────────────────────────────────────────────────────────────────────

fig, axes = plt.subplots(1, 3, figsize=(14, 4))
fig.suptitle('PSF Estimation Error Summary', fontsize=12)
method_names = list(METHODS.keys())
colors = ['#00bcd4', '#ff9800', '#8bc34a']
metrics = [('dL', 'ΔL (pixels)', 0, 15),
           ('dtheta', 'Δθ (degrees)', 0, 30),
           ('psf_l2', 'PSF L2 error', 0, None)]

for ax, (key, ylabel, ymin, ymax) in zip(axes, metrics):
    x = np.arange(n_cases)
    w = 0.25
    for i, (mname, col) in enumerate(zip(method_names, colors)):
        vals = [r[key] for r in results if r['method'] == mname]
        ax.bar(x + i*w, vals, width=w, label=mname, color=col, alpha=0.85)
    ax.set_xticks(x + w)
    ax.set_xticklabels([c['label'].split()[0] + '\n' + c['label'].split()[1]
                        for c in cases], fontsize=8)
    ax.set_ylabel(ylabel); ax.set_title(ylabel)
    ax.set_ylim(ymin, ymax)
    ax.legend(fontsize=8); ax.grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.savefig('psf_error_summary.png', dpi=130, bbox_inches='tight')
plt.show()

print('\nDone. Best method per case:')
for c in cases:
    case_res = [r for r in results if r['case'] == c['label']]
    best = min(case_res, key=lambda r: r['psf_l2'])
    print(f"  {c['label']:<22}  →  {best['method']:<14}  "
          f"L2={best['psf_l2']:.4f}  ΔL={best['dL']}  Δθ={best['dtheta']:.1f}°")


# ─────────────────────────────────────────────────────────────────────────────
# Wiener Deblurring with Cepstrum-estimated PSF
# Three variants to isolate where quality is lost:
#   (a) true PSF + oracle K   → upper bound
#   (b) cep PSF  + oracle K   → cost of PSF estimation error
#   (c) cep PSF  + blind K    → fully blind pipeline
# ─────────────────────────────────────────────────────────────────────────────

def wiener_oracle_K(g, psf, f_ref, K_range=np.logspace(-4, -1, 40)):
    best_K, best_p, best_rec = None, -np.inf, None
    for K in K_range:
        rec = wiener(g, psf, K)
        p   = psnr(f_ref, rec)
        if p > best_p:
            best_p, best_K, best_rec = p, K, rec
    return best_rec, best_K, best_p

def wiener_blind_K(g, psf, K_range=np.logspace(-4, -1, 40)):
    """
    Blind K: pick K minimising forward-model residual ||h*wiener(g,h,K) - g||.
    No f_true needed.
    """
    best_K, best_score, best_rec = None, -np.inf, None
    for K in K_range:
        rec   = wiener(g, psf, K)
        score = -np.linalg.norm(
            ndimage.convolve(rec, psf, mode='wrap') - g
        ) / (np.linalg.norm(g) + 1e-8)
        if score > best_score:
            best_score, best_K, best_rec = score, K, rec
    return best_rec, best_K

from skimage.metrics import structural_similarity as ssim

print(f"\n{'─'*78}")
print(f"  {'Case':<22}  {'Variant':<28}  {'PSNR':>6}  {'SSIM':>6}  {'K':>9}")
print(f"{'─'*78}")

wiener_results = []
for c in cases:
    h_cep, L_est, theta_est = estimate_psf_cepstrum(c['g'], PSF_SIZE, SIGMA_NOISE)

    rec_oracle, K_oracle, p_oracle = wiener_oracle_K(c['g'], c['psf'], f_true)
    s_oracle = ssim(f_true, rec_oracle, data_range=1.0)

    rec_est_ok, K_est_ok, p_est_ok = wiener_oracle_K(c['g'], h_cep, f_true)
    s_est_ok = ssim(f_true, rec_est_ok, data_range=1.0)

    rec_blind, K_blind = wiener_blind_K(c['g'], h_cep)
    p_blind = psnr(f_true, rec_blind)
    s_blind = ssim(f_true, rec_blind, data_range=1.0)

    p_blurred = psnr(f_true, c['g'])
    s_blurred = ssim(f_true, c['g'], data_range=1.0)

    for label, p, s, K in [
        ('Blurred input',            p_blurred, s_blurred, None),
        ('true PSF + oracle K',      p_oracle,  s_oracle,  K_oracle),
        ('cep PSF  + oracle K',      p_est_ok,  s_est_ok,  K_est_ok),
        ('cep PSF  + blind K ← blind', p_blind, s_blind,   K_blind),
    ]:
        Kstr = f'{K:.2e}' if K else '—'
        print(f"  {c['label']:<22}  {label:<28}  {p:>6.2f}  {s:>6.4f}  {Kstr:>9}")
    print(f"{'─'*78}")

    wiener_results.append({
        'case': c['label'], 'g': c['g'],
        'L_true': c['length'], 'theta_true': c['angle'],
        'L_est': L_est, 'theta_est': theta_est,
        'rec_oracle': rec_oracle, 'p_oracle': p_oracle, 's_oracle': s_oracle,
        'rec_est_ok': rec_est_ok, 'p_est_ok': p_est_ok, 's_est_ok': s_est_ok,
        'rec_blind':  rec_blind,  'p_blind':  p_blind,  's_blind':  s_blind,
        'p_blurred':  p_blurred,  's_blurred': s_blurred,
    })


# ── Full image comparison ─────────────────────────────────────────────────────

fig, axes = plt.subplots(len(cases), 5, figsize=(20, 4.5 * len(cases)))
fig.suptitle('Wiener — Cepstrum PSF Estimate vs Baselines', fontsize=13, y=1.01)
col_titles = [
    'Ground Truth',
    'Blurred+Noise',
    'Wiener\ntrue PSF + oracle K',
    'Wiener\ncep PSF + oracle K',
    'Wiener\ncep PSF + blind K  ★ fully blind',
]
for row, r in enumerate(wiener_results):
    imgs = [f_true, r['g'], r['rec_oracle'], r['rec_est_ok'], r['rec_blind']]
    subs = [
        'Ground Truth',
        f"PSNR={r['p_blurred']:.2f}  SSIM={r['s_blurred']:.4f}",
        f"PSNR={r['p_oracle']:.2f}  SSIM={r['s_oracle']:.4f}",
        f"PSNR={r['p_est_ok']:.2f}  SSIM={r['s_est_ok']:.4f}\n"
        f"L={r['L_est']} θ={r['theta_est']:.0f}° (true {r['L_true']} {r['theta_true']}°)",
        f"PSNR={r['p_blind']:.2f}  SSIM={r['s_blind']:.4f}",
    ]
    for col, (img, sub) in enumerate(zip(imgs, subs)):
        axes[row, col].imshow(img, cmap='gray', vmin=0, vmax=1)
        if row == 0: axes[row, col].set_title(col_titles[col], fontsize=9, pad=6)
        axes[row, col].set_xlabel(sub, fontsize=7.5)
        if col == 0: axes[row, col].set_ylabel(r['case'], fontsize=9)
        axes[row, col].set_xticks([]); axes[row, col].set_yticks([])

plt.tight_layout()
plt.savefig('wiener_cepstrum_results.png', dpi=130, bbox_inches='tight')
plt.show()


# ── Zoomed ROI ────────────────────────────────────────────────────────────────

ROI = np.s_[80:200, 90:230]
fig, axes = plt.subplots(len(cases), 4, figsize=(14, 4.5 * len(cases)))
fig.suptitle('Zoomed ROI — Edge Recovery', fontsize=13)
for row, r in enumerate(wiener_results):
    for col, (img, title) in enumerate([
        (f_true,          'Ground Truth'),
        (r['g'],          f"Blurred  {r['p_blurred']:.1f}dB"),
        (r['rec_oracle'], f"True PSF+oracle K  {r['p_oracle']:.1f}dB"),
        (r['rec_blind'],  f"Cep PSF+blind K  {r['p_blind']:.1f}dB  ★"),
    ]):
        axes[row, col].imshow(img[ROI], cmap='gray', vmin=0, vmax=1)
        axes[row, col].set_title(title, fontsize=9)
        if col == 0: axes[row, col].set_ylabel(r['case'], fontsize=9)
        axes[row, col].axis('off')

plt.tight_layout()
plt.savefig('wiener_zoomed_roi.png', dpi=130, bbox_inches='tight')
plt.show()

# ─────────────────────────────────────────────────────────────────────────────
# Post-Processing Cell — Ringing & Noise Removal after Wiener
# Requires: wiener_results, f_true from previous cells
# ─────────────────────────────────────────────────────────────────────────────

!pip install bm3d -q

import bm3d
from skimage.restoration import denoise_tv_chambolle, denoise_bilateral

def post_process(rec, sigma_est=0.02):
    """Apply TV, Bilateral, and BM3D to a Wiener-deblurred image."""
    tv      = denoise_tv_chambolle(rec, weight=0.08)
    bilat   = denoise_bilateral(rec, sigma_color=0.05, sigma_spatial=2)
    bm3d_out = bm3d.bm3d(rec, sigma_psd=sigma_est, stage_arg=bm3d.BM3DStages.ALL_STAGES)
    bm3d_out = np.clip(bm3d_out, 0, 1)
    return tv, bilat, bm3d_out

print(f"\n{'─'*82}")
print(f"  {'Case':<22}  {'Method':<28}  {'PSNR':>6}  {'SSIM':>6}  {'ΔPSNR':>7}  {'ΔSSIM':>7}")
print(f"{'─'*82}")

pp_results = []
for r in wiener_results:
    tv, bilat, bm3d_out = post_process(r['rec_blind'])

    metrics = {
        'blind_raw': (r['rec_blind'],  r['p_blind'],  r['s_blind']),
        'tv':        (tv,  psnr(f_true, tv),    ssim(f_true, tv,    data_range=1.0)),
        'bilateral': (bilat, psnr(f_true, bilat), ssim(f_true, bilat, data_range=1.0)),
        'bm3d':      (bm3d_out, psnr(f_true, bm3d_out), ssim(f_true, bm3d_out, data_range=1.0)),
    }

    labels = {
        'blind_raw':  'Blind Wiener (baseline)',
        'tv':         '+ TV denoising',
        'bilateral':  '+ Bilateral filter',
        'bm3d':       '+ BM3D          ★',
    }

    for key, (img, p, s) in metrics.items():
        dp = p - r['p_blind']
        ds = s - r['s_blind']
        dp_str = f"{dp:+.2f}" if key != 'blind_raw' else '—'
        ds_str = f"{ds:+.4f}" if key != 'blind_raw' else '—'
        print(f"  {r['case']:<22}  {labels[key]:<28}  {p:>6.2f}  {s:>6.4f}  {dp_str:>7}  {ds_str:>7}")
    print(f"{'─'*82}")

    pp_results.append({**r,
        'tv': tv, 'bilat': bilat, 'bm3d': bm3d_out,
        'metrics': metrics
    })


# ── Visual comparison ─────────────────────────────────────────────────────────

fig, axes = plt.subplots(len(pp_results), 5, figsize=(22, 4.5 * len(pp_results)))
fig.suptitle('Post-Processing Comparison (on top of blind Wiener)', fontsize=13, y=1.01)

col_titles = [
    'Ground Truth',
    'Blind Wiener\n(baseline)',
    '+ TV\ndenoising',
    '+ Bilateral\nfilter',
    '+ BM3D  ★',
]

ROI = np.s_[80:200, 90:230]   # same zoomed region as before

for row, r in enumerate(pp_results):
    _, (p_tv, s_tv)    = r['metrics']['tv'][1], (r['metrics']['tv'][1],    r['metrics']['tv'][2])
    _, (p_bi, s_bi)    = r['metrics']['bilateral'][1], (r['metrics']['bilateral'][1], r['metrics']['bilateral'][2])
    _, (p_bm, s_bm)    = r['metrics']['bm3d'][1], (r['metrics']['bm3d'][1],   r['metrics']['bm3d'][2])

    imgs = [f_true, r['rec_blind'], r['tv'], r['bilat'], r['bm3d']]
    subs = [
        'Ground Truth',
        f"PSNR={r['p_blind']:.2f}  SSIM={r['s_blind']:.4f}",
        f"PSNR={p_tv:.2f}  SSIM={s_tv:.4f}",
        f"PSNR={p_bi:.2f}  SSIM={s_bi:.4f}",
        f"PSNR={p_bm:.2f}  SSIM={s_bm:.4f}",
    ]
    for col, (img, sub) in enumerate(zip(imgs, subs)):
        axes[row, col].imshow(img[ROI], cmap='gray', vmin=0, vmax=1)
        if row == 0: axes[row, col].set_title(col_titles[col], fontsize=9, pad=6)
        axes[row, col].set_xlabel(sub, fontsize=8)
        if col == 0: axes[row, col].set_ylabel(r['case'], fontsize=9)
        axes[row, col].axis('off')

plt.tight_layout()
plt.savefig('post_processing_comparison.png', dpi=130, bbox_inches='tight')
plt.show()

# ─────────────────────────────────────────────────────────────────────────────
# Post-Processing Cell — Ringing & Noise Removal after Wiener
# Requires: wiener_results, f_true from previous cells
# ─────────────────────────────────────────────────────────────────────────────

!pip install bm3d -q

import bm3d
from skimage.restoration import denoise_tv_chambolle, denoise_bilateral
from skimage.filters import unsharp_mask

def post_process(rec, sigma_est=0.02):
    """Apply TV, Bilateral, and BM3D to a Wiener-deblurred image."""
    tv       = denoise_tv_chambolle(rec, weight=0.08)
    tv       = unsharp_mask(tv, radius=2.0, amount=1)
    bilat    = denoise_bilateral(rec, sigma_color=0.05, sigma_spatial=2)
    bm3d_out = bm3d.bm3d(rec, sigma_psd=sigma_est, stage_arg=bm3d.BM3DStages.ALL_STAGES)
    bm3d_out = np.clip(bm3d_out, 0, 1)
    return tv, bilat, bm3d_out

print(f"\n{'─'*82}")
print(f"  {'Case':<22}  {'Method':<28}  {'PSNR':>6}  {'SSIM':>6}  {'ΔPSNR':>7}  {'ΔSSIM':>7}")
print(f"{'─'*82}")

pp_results = []
for r in wiener_results:
    tv, bilat, bm3d_out = post_process(r['rec_blind'])

    metrics = {
        'blind_raw': (r['rec_blind'],  r['p_blind'],  r['s_blind']),
        'tv':        (tv,  psnr(f_true, tv),    ssim(f_true, tv,    data_range=1.0)),
        'bilateral': (bilat, psnr(f_true, bilat), ssim(f_true, bilat, data_range=1.0)),
        'bm3d':      (bm3d_out, psnr(f_true, bm3d_out), ssim(f_true, bm3d_out, data_range=1.0)),
    }

    labels = {
        'blind_raw':  'Blind Wiener (baseline)',
        'tv':         '+ TV + Unsharp Mask',
        'bilateral':  '+ Bilateral filter',
        'bm3d':       '+ BM3D          ★',
    }

    for key, (img, p, s) in metrics.items():
        dp = p - r['p_blind']
        ds = s - r['s_blind']
        dp_str = f"{dp:+.2f}" if key != 'blind_raw' else '—'
        ds_str = f"{ds:+.4f}" if key != 'blind_raw' else '—'
        print(f"  {r['case']:<22}  {labels[key]:<28}  {p:>6.2f}  {s:>6.4f}  {dp_str:>7}  {ds_str:>7}")
    print(f"{'─'*82}")

    pp_results.append({**r,
        'tv': tv, 'bilat': bilat, 'bm3d': bm3d_out,
        'metrics': metrics
    })


# ── Visual comparison ─────────────────────────────────────────────────────────

fig, axes = plt.subplots(len(pp_results), 5, figsize=(22, 4.5 * len(pp_results)))
fig.suptitle('Post-Processing Comparison (on top of blind Wiener)', fontsize=13, y=1.01)

col_titles = [
    'Ground Truth',
    'Blind Wiener\n(baseline)',
    '+ TV + Unsharp Mask',
    '+ Bilateral\nfilter',
    '+ BM3D  ★',
]

ROI = np.s_[80:200, 90:230]

for row, r in enumerate(pp_results):
    _, (p_tv, s_tv)    = r['metrics']['tv'][1], (r['metrics']['tv'][1],    r['metrics']['tv'][2])
    _, (p_bi, s_bi)    = r['metrics']['bilateral'][1], (r['metrics']['bilateral'][1], r['metrics']['bilateral'][2])
    _, (p_bm, s_bm)    = r['metrics']['bm3d'][1], (r['metrics']['bm3d'][1],   r['metrics']['bm3d'][2])

    imgs = [f_true, r['rec_blind'], r['tv'], r['bilat'], r['bm3d']]
    subs = [
        'Ground Truth',
        f"PSNR={r['p_blind']:.2f}  SSIM={r['s_blind']:.4f}",
        f"PSNR={p_tv:.2f}  SSIM={s_tv:.4f}",
        f"PSNR={p_bi:.2f}  SSIM={s_bi:.4f}",
        f"PSNR={p_bm:.2f}  SSIM={s_bm:.4f}",
    ]
    for col, (img, sub) in enumerate(zip(imgs, subs)):
        axes[row, col].imshow(img[ROI], cmap='gray', vmin=0, vmax=1)
        if row == 0: axes[row, col].set_title(col_titles[col], fontsize=9, pad=6)
        axes[row, col].set_xlabel(sub, fontsize=8)
        if col == 0: axes[row, col].set_ylabel(r['case'], fontsize=9)
        axes[row, col].axis('off')

plt.tight_layout()
plt.savefig('post_processing_comparison.png', dpi=130, bbox_inches='tight')
plt.show()

# ── Visual comparison ─────────────────────────────────────────────────────────

fig, axes = plt.subplots(len(pp_results), 5, figsize=(22, 4.5 * len(pp_results)))
fig.suptitle('Post-Processing Comparison (on top of blind Wiener)', fontsize=13, y=1.01)

col_titles = [
    'Ground Truth',
    'Blind Wiener\n(baseline)',
    '+ TV + Unsharp Mask',
    '+ Bilateral\nfilter',
    '+ BM3D  ★',
]

for row, r in enumerate(pp_results):
    _, (p_tv, s_tv)    = r['metrics']['tv'][1], (r['metrics']['tv'][1],    r['metrics']['tv'][2])
    _, (p_bi, s_bi)    = r['metrics']['bilateral'][1], (r['metrics']['bilateral'][1], r['metrics']['bilateral'][2])
    _, (p_bm, s_bm)    = r['metrics']['bm3d'][1], (r['metrics']['bm3d'][1],   r['metrics']['bm3d'][2])

    imgs = [f_true, r['rec_blind'], r['tv'], r['bilat'], r['bm3d']]
    subs = [
        'Ground Truth',
        f"PSNR={r['p_blind']:.2f}  SSIM={r['s_blind']:.4f}",
        f"PSNR={p_tv:.2f}  SSIM={s_tv:.4f}",
        f"PSNR={p_bi:.2f}  SSIM={s_bi:.4f}",
        f"PSNR={p_bm:.2f}  SSIM={s_bm:.4f}",
    ]
    for col, (img, sub) in enumerate(zip(imgs, subs)):
        axes[row, col].imshow(img, cmap='gray', vmin=0, vmax=1)
        if row == 0: axes[row, col].set_title(col_titles[col], fontsize=9, pad=6)
        axes[row, col].set_xlabel(sub, fontsize=8)
        if col == 0: axes[row, col].set_ylabel(r['case'], fontsize=9)
        axes[row, col].axis('off')

plt.tight_layout()
plt.savefig('post_processing_comparison.png', dpi=130, bbox_inches='tight')
plt.show()

# ── Visual comparison ─────────────────────────────────────────────────────────

fig, axes = plt.subplots(len(pp_results), 5, figsize=(22, 4.5 * len(pp_results)))
fig.suptitle('Post-Processing Comparison (on top of blind Wiener)', fontsize=13, y=1.01)

col_titles = [
    'Blurred+Noise',
    'Wiener\ntrue PSF + oracle K',
    'Blind K Wiener\n+ TV + Unsharp Mask',
    'Blind K Wiener\n+ Bilateral',
    'Blind K Wiener\n+ BM3D  ★',
]

for row, r in enumerate(pp_results):
    _, (p_tv, s_tv)   = r['metrics']['tv'][1],       (r['metrics']['tv'][1],       r['metrics']['tv'][2])
    _, (p_bi, s_bi)   = r['metrics']['bilateral'][1], (r['metrics']['bilateral'][1], r['metrics']['bilateral'][2])
    _, (p_bm, s_bm)   = r['metrics']['bm3d'][1],      (r['metrics']['bm3d'][1],      r['metrics']['bm3d'][2])

    imgs = [r['g'], r['rec_oracle'], r['tv'], r['bilat'], r['bm3d']]
    subs = [
        f"PSNR={r['p_blurred']:.2f}  SSIM={r['s_blurred']:.4f}",
        f"PSNR={r['p_oracle']:.2f}  SSIM={r['s_oracle']:.4f}",
        f"PSNR={p_tv:.2f}  SSIM={s_tv:.4f}",
        f"PSNR={p_bi:.2f}  SSIM={s_bi:.4f}",
        f"PSNR={p_bm:.2f}  SSIM={s_bm:.4f}",
    ]
    for col, (img, sub) in enumerate(zip(imgs, subs)):
        axes[row, col].imshow(img, cmap='gray', vmin=0, vmax=1)
        if row == 0: axes[row, col].set_title(col_titles[col], fontsize=9, pad=6)
        axes[row, col].set_xlabel(sub, fontsize=8)
        if col == 0: axes[row, col].set_ylabel(r['case'], fontsize=9)
        axes[row, col].axis('off')

plt.tight_layout()
plt.savefig('post_processing_comparison.png', dpi=130, bbox_inches='tight')
plt.show()

# ─────────────────────────────────────────────────────────────────────────────
# Summary Table
# ─────────────────────────────────────────────────────────────────────────────

import pandas as pd

rows = []
for r in pp_results:
    p_tv, s_tv   = r['metrics']['tv'][1],         r['metrics']['tv'][2]
    p_bi, s_bi   = r['metrics']['bilateral'][1],   r['metrics']['bilateral'][2]
    p_bm, s_bm   = r['metrics']['bm3d'][1],        r['metrics']['bm3d'][2]

    rows += [
        {'Case': r['case'], 'Stage': 'Blurred + Noise',               'PSNR': r['p_blurred'], 'SSIM': r['s_blurred']},
        {'Case': r['case'], 'Stage': 'Wiener — True PSF + Oracle K',  'PSNR': r['p_oracle'],  'SSIM': r['s_oracle']},
        {'Case': r['case'], 'Stage': 'Wiener — Blind K (cep PSF)',    'PSNR': r['p_blind'],   'SSIM': r['s_blind']},
        {'Case': r['case'], 'Stage': 'Blind K Wiener + TV + Unsharp', 'PSNR': p_tv,           'SSIM': s_tv},
        {'Case': r['case'], 'Stage': 'Blind K Wiener + Bilateral',    'PSNR': p_bi,           'SSIM': s_bi},
        {'Case': r['case'], 'Stage': 'Blind K Wiener + BM3D',         'PSNR': p_bm,           'SSIM': s_bm},
    ]

df = pd.DataFrame(rows)
df['PSNR'] = df['PSNR'].round(2)
df['SSIM'] = df['SSIM'].round(4)

# ── Styled display ────────────────────────────────────────────────────────────

def highlight_best(df):
    styled = df.copy().astype(str)
    for case in df['Case'].unique():
        mask = df['Case'] == case
        for metric in ['PSNR', 'SSIM']:
            best_idx = df.loc[mask, metric].idxmax()
            styled.loc[best_idx, metric] = f"✦ {df.loc[best_idx, metric]}"
    return styled

df_display = highlight_best(df)

# Group by case with dividers
print(f"\n{'═'*70}")
print(f"  {'PIPELINE SUMMARY':^66}")
print(f"{'═'*70}")
print(f"  {'Case':<22}  {'Stage':<34}  {'PSNR':>6}  {'SSIM':>7}")
print(f"{'─'*70}")

prev_case = None
for _, row in df_display.iterrows():
    if prev_case and row['Case'] != prev_case:
        print(f"{'─'*70}")
    print(f"  {row['Case']:<22}  {row['Stage']:<34}  {row['PSNR']:>6}  {row['SSIM']:>7}")
    prev_case = row['Case']

print(f"{'═'*70}")
print("  ✦ = best per case per metric")

# ── Also show as DataFrame for Colab's rich display ──────────────────────────
display(df.style
    .format({'PSNR': '{:.2f}', 'SSIM': '{:.4f}'})
    .background_gradient(subset=['PSNR'], cmap='YlGn')
    .background_gradient(subset=['SSIM'], cmap='YlGn')
    .set_properties(**{'text-align': 'left'})
    .set_table_styles([
        {'selector': 'th', 'props': [('font-weight', 'bold'), ('text-align', 'left')]},
        {'selector': 'tr:hover', 'props': [('background-color', '#2a2a2a')]},
    ])
)