# -*- coding: utf-8 -*-
"""Multiframe_denoising.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13l41zhi_UOGC3Fv0oNBpaRttPJuyaxvX
"""

import os
import cv2

print(os.listdir('/content'))

import cv2
images =[]

for i in range(1,8):
  path = f"/content/im{i}.png"
  img = cv2.imread(path,cv2.IMREAD_GRAYSCALE)

  images.append(img)

print('Length of the image folder:',len(images))

from google.colab.patches import cv2_imshow
ref_image = images[3];

pastimg=[];
for i in range(0,3):
 img = images[i];
 pastimg.append(img)

len(pastimg)

"""separated our frames as past images to apply backward optical flow for t-3 frames."""

futureimg= [];
for i in range(4,7):
 img = images[i];
 futureimg.append(img)

len(futureimg)

"""separated our frames as future images to apply forward optical flow for t+3 frames."""

flow_p =[]
for i in range(0,3):
  flow = cv2.calcOpticalFlowFarneback(
    pastimg[i], ref_image,
    None,
    pyr_scale=0.5,
    levels=3,
    winsize=15,
    iterations=3,
    poly_n=5,
    poly_sigma=1.2,
    flags=0
)
  flow_p.append(flow)
len(flow_p)

"""Motion vectors generated by the forward optical flow algorithm for all 3 past frames are stored in the flow_p vector."""

flow_f =[]
for i in range(0,3):
  flow = cv2.calcOpticalFlowFarneback(
    ref_image,futureimg[i],
    None,
    pyr_scale=0.5,
    levels=3,
    winsize=15,
    iterations=3,
    poly_n=5,
    poly_sigma=1.2,
    flags=0

)
  flow_f.append(flow)
len(flow_f)

import numpy as np
[H,W] = ref_image.shape
print(H,W)
flow_f = np.array(flow_f)
flow_p = np.array(flow_p)

def warp_frame(src,flow_p):
  x = np.arange(0,W)
  y = np.arange(0,H)
  x,y = np.meshgrid(x,y)
  return cv2.remap(src,x+flow_p[:,:,0],y+flow_p[:,:,1],cv2.INTER_CUBIC, borderMode=cv2.BORDER_REPLICATE)

def warp_frame(src,flow_f):
  x = np.arange(0,W)
  y = np.arange(0,H)
  x,y = np.meshgrid(x,y)
  return cv2.remap(src,x-flow_f[:,:,0],y-flow_f[:,:,1],cv2.INTER_CUBIC, borderMode=cv2.BORDER_REPLICATE)

import numpy as np
import cv2

# Redefine the warp_frame function with the fix to ensure map types are float32
def warp_frame(src, flow_p):
  # Create coordinate grids, ensuring float32 type
  x = np.arange(0, W, dtype=np.float32)
  y = np.arange(0, H, dtype=np.float32)
  x_grid, y_grid = np.meshgrid(x, y)

  # Calculate the warped coordinates and explicitly cast to float32
  map_x = (x_grid + flow_p[:,:,0]).astype(np.float32)
  map_y = (y_grid + flow_p[:,:,1]).astype(np.float32)

  return cv2.remap(src, map_x, map_y, cv2.INTER_LINEAR, borderMode=cv2.BORDER_REPLICATE)

warped_frames = []
for i in range(3):
    warped = warp_frame(futureimg[i], flow_p[i])
    warped_frames.append(warped)

def warp_frame(src, flow_f):
  # Create coordinate grids, ensuring float32 type
  x = np.arange(0, W, dtype=np.float32)
  y = np.arange(0, H, dtype=np.float32)
  x_grid, y_grid = np.meshgrid(x, y)

  # Calculate the warped coordinates and explicitly cast to float32
  map_x = (x_grid - flow_f[:,:,0]).astype(np.float32)
  map_y = (y_grid - flow_f[:,:,1]).astype(np.float32)

  return cv2.remap(src, map_x, map_y, cv2.INTER_LINEAR, borderMode=cv2.BORDER_REPLICATE)

warped_frames_f = []
for i in range(3):
    warped = warp_frame(pastimg[i], flow_f[i])
    warped_frames_f.append(warped)

all_warped = warped_frames + warped_frames_f
residuals = [w.astype(np.float32) - ref_image.astype(np.float32) for w in all_warped]

len(residuals)
cv2_imshow(residuals[2])
residual_magnitudes = [np.mean(np.abs(r)) for r in residuals]

import matplotlib.pyplot as plt
plt.bar(range(len(residual_magnitudes)), residual_magnitudes)
plt.xlabel('Frame')
plt.ylabel('Residual magnitude')
plt.show()

def block_ssim_aggregate(ref, all_warped, block_size=64):
    H, W = ref.shape
    pad_h = (block_size - H % block_size) % block_size
    pad_w = (block_size - W % block_size) % block_size

    ref_pad = np.pad(ref, ((0, pad_h), (0, pad_w)), mode='reflect')
    warped_pad = [np.pad(w, ((0, pad_h), (0, pad_w)), mode='reflect') for w in all_warped]

    H_pad, W_pad = ref_pad.shape
    output = np.zeros((H_pad, W_pad), dtype=np.float32)

    for by in range(0, H_pad, block_size):
        for bx in range(0, W_pad, block_size):
            ref_block = ref_pad[by:by+block_size, bx:bx+block_size]
            block_scores, block_patches = [], []
            for w in warped_pad:
                patch = w[by:by+block_size, bx:bx+block_size]
                score = ssim(ref_block, patch, data_range=255)
                block_scores.append(score)
                block_patches.append(patch)

            patches = block_patches + [ref_block]
            scores = block_scores + [1.0]
            weights = np.array(scores)
            weights = (weights / weights.sum())**1.1
            output[by:by+block_size, bx:bx+block_size] = np.average(patches, axis=0, weights=weights)

    return np.clip(output[:H, :W], 0, 255).astype(np.uint8)

"""Alternate"""

from skimage.metrics import structural_similarity as ssim
result = block_ssim_aggregate(ref_image, all_warped, block_size=64)
cv2_imshow(result)
ssim_score = ssim(ref_image, result, data_range=255)
psnr_score = psnr(ref_image, result, data_range=255)
print(f"SSIM Score: {ssim_score}")
print(f"PSNR Score: {psnr_score}")
mse = np.mean((result - ref_image) )
print(f"MSE: {mse}")

def sigma_filter(image, sigma, window_size):
    """
    Sigma filter: for each pixel, average only neighbors within
    [pixel_value - sigma, pixel_value + sigma] intensity range.
    Preserves edges better than a plain Gaussian blur.

    Args:
        image:       Input grayscale image (H, W) uint8
        sigma:       Intensity range threshold (e.g. 10-30)
                     Only pixels within +/- sigma of center pixel are averaged
        window_size: Spatial neighborhood size (must be odd, e.g. 3, 5, 7)

    Returns:
        Filtered image (H, W) uint8
    """
    if window_size % 2 == 0:
        window_size += 1
        print(f'window_size adjusted to {window_size} (must be odd)')

    pad = window_size // 2
    img = image.astype(np.float32)
    img_pad = np.pad(img, pad, mode='reflect')

    # Shape: (H, W, window_size, window_size)
    windows = sliding_window_view(img_pad, (window_size, window_size))

    # Center pixel for each location — shape (H, W, 1, 1)
    center = img[:, :, np.newaxis, np.newaxis]

    # Mask: only neighbors within sigma range of center pixel
    mask = np.abs(windows - center) <= sigma

    # Average only qualifying pixels
    output = (windows * mask).sum(axis=(2, 3)) / mask.sum(axis=(2, 3))

    return np.clip(output, 0, 255).astype(np.uint8)

image = result

sigma       = 5  # user input
window_size = 20   # user input
result_sf = sigma_filter(image, sigma=sigma, window_size=window_size)
cv2.imwrite('sigma_filtered.png', result)
cv2_imshow(result_sf)
ssim_score = ssim(ref_image, result_sf, data_range=255)
psnr_score = psnr(ref_image, result_sf, data_range=255)
print(f"SSIM Score: {ssim_score}")
print(f"PSNR Score: {psnr_score}")
mse = np.mean((result_sf - ref_image) ** 2)
print(f"MSE: {mse}")

import numpy as np
import cv2

def unsharp_mask(image, kernel_size=5, sigma=1.0, amount=1.0):
    """
    Linear unsharp mask sharpening filter.

    Process:
        blurred   = Gaussian blur of image
        mask      = image - blurred        (high frequency detail)
        sharpened = image + amount * mask  (enhance the detail)

    Args:
        image:       Input grayscale image (H, W) uint8
        kernel_size: Gaussian blur kernel size (must be odd, e.g. 3, 5, 7)
        sigma:       Gaussian blur sigma (spread of blur)
        amount:      Strength of sharpening (e.g. 0.5 subtle, 1.0 standard, 2.0 strong)

    Returns:
        Sharpened image (H, W) uint8
    """
    if kernel_size % 2 == 0:
        kernel_size += 1
        print(f'kernel_size adjusted to {kernel_size} (must be odd)')

    img = image.astype(np.float32)

    # Step 1 — Gaussian blur (low frequency component)
    blurred = cv2.GaussianBlur(img, (kernel_size, kernel_size), sigma)

    # Step 2 — Unsharp mask (high frequency detail)
    mask = img - blurred

    # Step 3 — Add scaled mask back to original
    sharpened = img + amount * mask

    return np.clip(sharpened, 0, 255).astype(np.uint8)

# image = cv2.imread('input.png', cv2.IMREAD_GRAYSCALE)
    # Using the 'result' from previous operations as the input image
    input_image = result_sf

    kernel_size = 11    # user input — larger = captures broader detail
    sigma       = 3  # user input — larger = more blur before sharpening
    amount      = 0.60 # user input — larger = stronger sharpening

    result_mf_s = unsharp_mask(input_image, kernel_size=kernel_size, sigma=sigma, amount=amount)

    cv2.imwrite('sharpened_output.png', result)
    cv2_imshow(result_mf_s)
    ssim_score = ssim(ref_image, result_mf_s, data_range=255)
    psnr_score = psnr(ref_image, result_mf_s, data_range=255)
    print(f"SSIM Score: {ssim_score}")
    print(f"PSNR Score: {psnr_score}")
    mse = np.mean((result_mf_s - ref_image) ** 2)
    print(f"MSE: {mse}")

cv2_imshow(ref_image)

